---
- hosts: localhost
  tasks:
    - name: Add apt key from keyserver
      apt_key: keyserver={{ item.keyserver }} id={{ item.id }}
      sudo: yes
      with_items:
        - { keyserver: 'hkp://keyserver.ubuntu.com:80', id: 94558F59 }
        - { keyserver: 'pgp.mit.edu', id: 5044912E }

    - name: Add apt key via url
      apt_key: url={{ item }} state=present
      sudo: yes
      with_items:
        - 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
        - 'http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc'

    - name: Add apt repositories
      apt_repository: repo='{{ item }}' state=present
      sudo: yes
      with_items:
        - deb http://repository.spotify.com stable non-free
        - deb http://dl.google.com/linux/chrome/deb/ stable main
        - deb http://download.virtualbox.org/virtualbox/debian trusty contrib
        - deb http://linux.dropbox.com/ubuntu trusty main
        - ppa:libreoffice/ppa
        - ppa:webupd8team/java

    - name: Purge existing libreoffice
      apt: name=libreoffice* state=absent purge=yes 
      sudo: yes

    - name: Update apt cache
      apt: update_cache=yes
      sudo: yes

    - name: Install apt packages
      apt: name={{ item }} state=latest
      sudo: yes
      with_items:
        - spotify-client
        - google-chrome-stable
        - virtualbox-4.3
        - gdm
        - network-manager-gnome
        - dropbox
        - curl
        - rlwrap
        - vim
        - emacs24
        - build-essential
        - traceroute
        - git
        - meld

    - name: Download Anaconda python distribution
      sudo: no
      get_url:
        url: https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda-2.2.0-Linux-x86_64.sh
        mode: 0755
        dest: ~/Anaconda.sh
        force: no

    - name: Install Anaconda
      command: bash ~/Anaconda.sh -b -p ~/anaconda creates=~/anaconda

    - name: Update Anaconda command-line utility
      command: "~/anaconda/bin/conda update conda"

    - name: Update Anaconda packages
      command: "~/anaconda/bin/conda update anaconda"

    - name: Remove Anaconda.sh
      file: path=~/Anaconda.sh state=absent

    - name: Autoaccept license for Java
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
      sudo: yes

    - name: Install Java 8
      apt: name=oracle-java8-installer state=latest install_recommends=yes
      sudo: yes

    - name: Set Java Environment variables
      apt: name=oracle-java8-set-default state=latest install_recommends=yes
      sudo: yes

    - name: Clone dotfiles
      git: repo=https://github.com/rolyv/dotfiles.git dest=~